import mysql.connector as c
y=c.connect(host="localhost",user="root",password="sql123",database="test1")
cr=y.cursor()
cr.execute("select * from marks")
print(cr.fetchmany(55))
y.commit()
cr.execute("desc marks")

print(cr.fetchall())
1y.commit()
cr.execute("insert into marks values(12,'B','M','ttt',8,6)")
y.commit()
print(cr.fetchall())
cr.execute("insert into marks values(12,'B','M','ttt',8,6)")
y.commit()
y.commit()
print(cr.fetchall())
cr.execute("select * from marks")
print(cr.fetchall())
print(cr.rowcount, "records inserted")
